Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.network "forwarded_port", guest: 1433, host: 1433
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "3096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y docker
    sudo service docker restart
    sudo docker pull microsoft/mssql-server-linux:2017-latest
    sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password123' \
   -p 1433:1433 --name sql1 \
   -d microsoft/mssql-server-linux:2017-latest
  SHELL
end
