# -*- mode: ruby -*-
# vi: set ft=ruby :
servers=[
  {
    :hostname => "web",
    :ip => "192.168.100.10",
    :box => "centos/7",
    :ram => 512,
    :cpu => 2
  },
  {
    :hostname => "db",
    :ip => "192.168.100.11",
    :box => "centos/7",
    :ram => 512,
    :cpu => 4
  }
]
Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "public_network"
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        end
    end
end
